version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=dbms_asmt
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - db_asmt:/var/lib/mysql
    networks:
      - php_docker

  www:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - php_docker

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - php_docker

networks:
  php_docker:
    driver: bridge

volumes:
  db_asmt: